### ISSUE TITLE
Lack of dropshadow makes icons less clear when panel is translucent

### ISSUE THREAD

**Issue by galgalesh** [CanonicalLtd/desktop-design#51] opened 2017-12-18 17:12 UTC
The Ambiance gnome-shell theme removes the dropshadow from icons in the top panel. This causes icons with similar colors to the background to be less clear.

# Ambiance

![image](https://user-images.githubusercontent.com/1492981/34118375-d507fa00-e41e-11e7-8d12-4437bdcdf41c.png)

# Adwaita

![image](https://user-images.githubusercontent.com/1492981/34118299-9a57ebc2-e41e-11e7-9e59-6a0f892b829e.png)

Especially for a colorblind person like me, the green in the battery is very hard to see in the ambiance theme.

**Comment by matthewpaulthomas** [comment] 2018-01-11 09:10
Thanks for this report, @galgalesh. We’ll try to tackle this as part of upcoming theme accessibility fixes.

**Comment by 8none1** [comment] 2018-01-11 09:58
I can't reproduce this on Artful.  I only have a black & white symbolic icon.

Any pointers here?  But, based on the screenshots above, yes, lets fix this.  Free for anyone to claim and work on.  Perhaps the Ambience RW theme can help here?  @3v1no

**Comment by galgalesh** [comment] 2018-01-11 10:02
You should be able to reproduce this with the "suru" icon theme, which doesn't have a dropshadow in the icon theme itself. I think the default icon theme has a dropshadow already in the icon theme.

**Comment by 3v1n0** [comment] 2018-01-11 15:56
@galgalesh such shadows are generated only by gnome-shell... There's a special css flag for that on g-s .css in order to control it (`icon-shadow`, see https://github.com/GNOME/gnome-shell-sass/blob/master/_common.scss#L792)

**Comment by 8none1** [comment] 2018-06-25 13:51
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.

**Closed by 8none1** 2018-06-25 13:51 UTC
Labels: Community team, Desktop team
