### ISSUE TITLE
GTK2 apps gradient on maximised windows

### ISSUE THREAD

**Issue by kwm14** [CanonicalLtd/desktop-design#47] opened 2017-11-30 17:00 UTC

**Comment by 3v1n0** [comment] 2018-01-23 14:10
Can you please be more specific on this one?

**Comment by 8none1** [comment] 2018-01-23 14:47
@didrocks Can you remember what this one was?

**Comment by didrocks** [comment] 2018-01-23 15:00
How come @3v1n0 have forgotten this! ;)
Basically:
Maximize a GTK2 apps, like thunderbird. Put it in the background, the backdrop is "flat", with a dark titlebar clashing with the menu not changing color.

GTK3 app, menu matches titlebar: https://preview.ibb.co/k4pjPG/Capture_d_cran_de_2018_01_23_15_54_20.png
GTK2 app, menu doesn't match titlebar: https://preview.ibb.co/cEuJjG/Capture_d_cran_de_2018_01_23_15_54_27.png

**Comment by 3v1n0** [comment] 2018-01-23 18:47
As mentioned in the meeting, the problem isn't GTK2, as both thunderbird and firefox now use GTK3, but it's due to their usage of the style context that is missing some classes which allow us to do such theming.

I've already submitted the [bug upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1407824) months ago, if no one from mozilla (I'll meet a friend working there next week, so maybe...) can fix this, I'll come with a solution, but if we have other designed options, that would decrease the priority.

**Comment by spencerbygraves** [comment] 2018-01-24 10:39
@3v1n0 Our design related to this can be found [in this issue](https://github.com/CanonicalLtd/desktop-design/issues/36#issuecomment-358338949). It looks most similar to GTK3.

**Comment by 3v1n0** [comment] 2018-01-24 10:49
@spencerbygraves that solution doesn't apply to ambiance. It's ok for new community theme, but not for the current ubuntu default theme.

**Comment by spencerbygraves** [comment] 2018-01-25 15:28
After talking to @3v1n0, we feel it would be best to use the existing design for the ambiance theme. Hopefully the issue will be fixed upstream.

**Comment by 8none1** [comment] 2018-06-25 13:51
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.

**Closed by 8none1** 2018-06-25 13:51 UTC
Labels: Desktop team
